#!/usr/bin/env python3
"""Generate docs/LEVELS.md status board from disk + levels.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEVELS_DIR = ROOT / "assets" / "converted" / "levels"
FLOW = ROOT / "assets" / "converted" / "levels.json"
META = ROOT / "assets" / "converted" / "wdl_meta.json"
DIRECTOR = ROOT / "scripts" / "engine" / "wdl_director.gd"
OUT = ROOT / "docs" / "LEVELS.md"

CUSTOM = {
    "start": "_begin_start",
    "studio": "_begin_studio",
    "town": "_begin_town",
    "shiks": "_begin_shiks",
    "plane": "_begin_plane",
}


def main() -> int:
    flow = json.loads(FLOW.read_text(encoding="utf-8")) if FLOW.exists() else {"levels": {}}
    meta = json.loads(META.read_text(encoding="utf-8")) if META.exists() else {"levels": {}}
    director = DIRECTOR.read_text(encoding="utf-8", errors="replace") if DIRECTOR.exists() else ""

    json_stems = {p.stem.lower(): p.stem for p in LEVELS_DIR.glob("*.json")}
    brushes = {p.stem.replace("_brush", "").lower() for p in LEVELS_DIR.glob("*_brush.glb")}

    # Prefer canonical names from levels.json; fall back to on-disk JSON stems.
    seen_lower: set[str] = set()
    names: list[str] = []
    for name in sorted(flow.get("levels", {}).keys(), key=str.lower):
        seen_lower.add(name.lower())
        names.append(name)
    for low, stem in sorted(json_stems.items()):
        if low not in seen_lower:
            seen_lower.add(low)
            names.append(stem)

    lines = [
        "# Level pack status",
        "",
        "Generated by `tools/build_level_board.py`. DoD = fresh JSON + brush (if WMB) +",
        "sky meta + generic cams **or** custom director. Goal: uniform pipeline, not per-level hacks.",
        "",
        "| Level | JSON | angle_gs | Brush | scene_map | Director |",
        "|-------|------|----------|-------|-----------|----------|",
    ]

    for name in names:
        key = name.lower()
        jp = LEVELS_DIR / f"{json_stems.get(key, name)}.json"
        has_json = jp.exists()
        has_ags = False
        if has_json:
            txt = jp.read_text(encoding="utf-8", errors="replace")
            has_ags = "angle_gs" in txt
        has_brush = key in brushes
        m = meta.get("levels", {}).get(key, {})
        scene = m.get("scene_map") or ("(indoor)" if m.get("indoor") else "")
        custom = next((k for k, fn in CUSTOM.items() if k == key and fn in director), "")
        director_cell = f"custom:{custom}" if custom else ("generic" if has_json else "—")
        lines.append(
            f"| {name} | {'yes' if has_json else 'NO'} | {'yes' if has_ags else 'no'} | "
            f"{'yes' if has_brush else '—'} | {scene or '—'} | {director_cell} |"
        )

    lines.append("")
    lines.append(f"Totals: {len(names)} levels, {len(brushes)} brushes, {len(CUSTOM)} custom directors.")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
