#!/usr/bin/env python3
"""Standalone WMB -> browser 3D viewer. Independent of the Godot pipeline.

Fresh, self-contained WMB entity/light/path parser (does not import
extract_wmb_full.py or gs_math.py -- written new, on purpose, so this is a
genuinely separate code path from the production converter/Godot spawn code,
not a wrapper around it) plus a tiny local HTTP server that serves a
Three.js viewer of the result. The point: judge entity placement/facing
directly against the raw parsed data, in a browser, with no Godot editor,
no headless rendering, no import cache -- and no dependency on this
session's own tool-execution environment, which has no working GPU context.

The entity rotation math (Conitec ang_to_matrix conjugated into a
right-handed Y-up basis) is implemented TWICE, independently: once here in
Python (for sanity printing) and once fresh in the browser's JavaScript
(see the embedded viewer HTML below). If both agree with what Godot shows,
that's real cross-validation, not two copies of the same bug.

Usage:
    python tools/wmb_web_viewer.py            # opens on Start, port 8765
    python tools/wmb_web_viewer.py Shiks --port 8765 --no-browser

Then open the printed URL (or it opens automatically).

2026-08-20: extended into a real live validation tool (the original
ask -- "validate lights, object placement, playability without running the
engine every time") rather than just a read-only position/facing checker:

  - LEVEL SWITCHING is live in the browser (a dropdown, no server restart)
    -- the server itself is level-agnostic now, parsing/caching whichever
    level's own /api/level.json?level=X is requested.
  - LIGHTS tab: every light's energy/range/color is a live slider,
    starting from calibrate_lights()'s own faithful mirror of the real
    Godot game's `_spawn_light()` / `_cap_saturated_light_ranges()` math
    (GB-44 through GB-49's actual shipped values, not raw WMB data) --
    plus global sliders for ambient and a simple elevation/azimuth sun
    (an approximation of Godot's Sun DirectionalLight3D, not a bit-exact
    replica of its rotation_degrees basis). "Copy current tuning as JSON"
    dumps the live state so a human can hand back a concrete numeric
    change list instead of a screenshot and a feeling.
  - PLACEMENT tab: raycasts every entity straight down onto the brush
    floor and flags a large gap (floating or embedded) with a colored
    marker + sortable list -- the same class of check as this project's
    own feet-snap policy (docs/CONTRACT.md #3), but interactive and
    instant instead of a per-candidate headless Godot run.
  - WALK tab: a simple pointer-lock FPS camera, floor-snapped each frame
    by raycasting down against the brush (no wall collision yet) -- good
    enough to eyeball scale, sightlines, and floor height without the
    real player controller.

Brush/entity meshes are generated on demand into tools/.web_cache/ (see
ensure_cache_warm()) by literally the same two offline scripts
(extract_wmb_mesh.py, convert_mdl.py) that used to populate
assets/converted/{levels,mdl}/ before this branch (zero-py-no-assets)
moved the SHIPPED game to parsing WMB/MDL directly at runtime instead --
this cache is dev-tool-only, .gitignore'd, and never touches that runtime
path. First request for a level takes a beat while its cache warms;
every later request/level-switch is instant.

The entity rotation math (Conitec ang_to_matrix conjugated into a
right-handed Y-up basis) is implemented TWICE, independently: once here in
Python (for sanity printing) and once fresh in the browser's JavaScript
(see the embedded viewer HTML below). If both agree with what Godot shows,
that's real cross-validation, not two copies of the same bug.
"""
from __future__ import annotations

import argparse
import json
import math
import struct
import sys
import threading
import webbrowser
from functools import partial
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]
WMB_SRC_DIR = ROOT / "original" / "piposh3d" / "WMB"
# 2026-08-20: this branch (zero-py-no-assets) deliberately deleted
# assets/converted/{levels,mdl} for the SHIPPED game -- Godot now parses WMB/
# MDL directly at runtime instead (see wmb_file.gd / mdl reader). This dev
# tool still wants real brush/character meshes to judge placement against,
# so it keeps its own on-demand cache, generated by literally the same two
# offline scripts that used to feed assets/converted/ (extract_wmb_mesh.py,
# convert_mdl.py) -- .gitignore'd, regenerable, never touches the shipped
# game's own runtime path. See ensure_cache_warm() below.
CACHE_DIR = ROOT / "tools" / ".web_cache"
MDL_GLB_DIR = CACHE_DIR / "mdl"
WMB_GLB_DIR = CACHE_DIR / "wmb"
LEVEL_JSON_DIR = CACHE_DIR / "levels"


def ensure_cache_warm(level: str) -> None:
    """Generates this level's own brush .glb (if missing) plus every MDL
    .glb referenced by it (if missing), via the same two offline scripts
    that used to populate assets/converted/ before this branch moved the
    shipped game to runtime WMB parsing. Self-healing: a fresh checkout, or
    a level nobody's opened in the viewer yet, "just works" on first
    request instead of needing a manual pre-conversion step remembered and
    run by hand."""
    import subprocess

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    brush_path = LEVEL_JSON_DIR / f"{level}_brush.glb"
    if not brush_path.exists():
        print(f"  [cache] generating brush geometry for {level}...")
        subprocess.run(
            [
                sys.executable,
                str(ROOT / "tools" / "extract_wmb_mesh.py"),
                "--only",
                level,
                "--dst-levels",
                str(LEVEL_JSON_DIR),
                "--dst-wmb",
                str(WMB_GLB_DIR),
            ],
            check=False,
            cwd=str(ROOT / "tools"),
        )

    wmb_path = None
    for ext in (".WMB", ".wmb"):
        cand = WMB_SRC_DIR / (level + ext)
        if cand.exists():
            wmb_path = cand
            break
    if wmb_path is None:
        return
    level_data = parse_wmb(wmb_path)
    stems = sorted(
        {
            Path(e["file"]).stem
            for e in level_data["entities"]
            if e["file"] and e["file"].lower().endswith(".mdl")
        }
    )
    missing = [s for s in stems if not (MDL_GLB_DIR / f"{s}.glb").exists()]
    if missing:
        print(f"  [cache] generating {len(missing)} character/prop model(s) for {level}...")
        subprocess.run(
            [
                sys.executable,
                str(ROOT / "tools" / "convert_mdl.py"),
                "--only",
                *missing,
                "--dst",
                str(MDL_GLB_DIR),
            ],
            check=False,
            cwd=str(ROOT / "tools"),
        )


# --- Light calibration, mirroring wmb_level_loader.gd's _spawn_light() /
# _cap_saturated_light_ranges() EXACTLY (GB-44 through GB-49's own real,
# shipped values) -- so what this viewer shows as each light's starting
# energy/range is the same number the real Godot game actually renders
# with, not the raw uncalibrated WMB value. Without this the viewer would
# be validating a fictional light setup nobody ships.
SATURATION_THRESHOLD = 0.3
COLOR_DIFF_THRESHOLD = 0.5
RANGE_CAP_FRACTION = 1.2
RANGE_CAP_FLOOR = 60.0
BASE_ENERGY = 1000.0
ENERGY_SCALE_REFERENCE_RANGE = 500.0
RANGE_CLAMP_MIN = 20.0
RANGE_CLAMP_MAX = 4000.0


def calibrate_lights(lights: list[dict]) -> None:
    """Mutates each light dict in place, adding `calibrated_range` and
    `calibrated_energy` -- the actual values the real Godot game's
    `_spawn_light()` would compute for this exact light, given every other
    light in the same level (the saturated-color anti-bleed cap needs the
    whole level's own light list, not just one light in isolation)."""
    for light in lights:
        rng = float(light.get("range", 300.0))
        light["raw_range"] = rng
        light["calibrated_range"] = max(RANGE_CLAMP_MIN, min(rng, RANGE_CLAMP_MAX))
        energy_scale = min(1.0, ENERGY_SCALE_REFERENCE_RANGE / max(rng, 1.0))
        light["calibrated_energy"] = BASE_ENERGY * energy_scale

    saturated = []
    for light in lights:
        c = light["color"]
        sat = max(c) - min(c)
        if sat > SATURATION_THRESHOLD:
            saturated.append(light)

    for i, li in enumerate(saturated):
        nearest = math.inf
        for j, lj in enumerate(saturated):
            if i == j:
                continue
            cd = math.dist(li["color"], lj["color"])
            if cd <= COLOR_DIFF_THRESHOLD:
                continue
            d = math.dist(li["pos"], lj["pos"])
            nearest = min(nearest, d)
        if nearest < math.inf:
            cap = max(nearest * RANGE_CAP_FRACTION, RANGE_CAP_FLOOR)
            li["calibrated_range"] = min(li["calibrated_range"], cap)


# --- Fresh WMB parse (independent of tools/extract_wmb_full.py) -----------


def _c_str(raw: bytes) -> str:
    return raw.split(b"\x00", 1)[0].decode("latin-1", errors="replace")


def _read_lists(data: bytes, n: int = 20) -> list[tuple[int, int]]:
    """WMB directory: a fixed-size table of (offset, length) pairs right
    after the 4-byte magic. Every chunk (objects, planes, textures, ...) is
    addressed through this table -- list index 15 is the object list for
    the WMB5 layout this game uses (confirmed by extract_wmb_full.py
    working across all 57 levels; re-verified here independently by
    checking every list's offset+length stays in-bounds)."""
    lists: list[tuple[int, int]] = []
    off = 4
    for _ in range(n):
        if off + 8 > len(data):
            break
        lo, ln = struct.unpack_from("<II", data, off)
        off += 8
        if ln == 0 and lo == 0:
            lists.append((lo, ln))
            continue
        if lo >= len(data) or lo + ln > len(data):
            break
        lists.append((lo, ln))
    return lists


def pos_gs_to_three(x: float, y: float, z: float) -> list[float]:
    """Acknex RHZUP (+X east, +Y north, +Z up) -> right-handed Y-up.
    Same target space as Godot: (x, y, z)_gs -> (x, z, -y). Three.js is
    also right-handed Y-up, so this is directly usable with no extra flip.
    """
    return [float(x), float(z), float(-y)]


def scale_gs_to_three(sx: float, sy: float, sz: float) -> list[float]:
    return [float(sx), float(sz), float(sy)]


def _norm_tilt(tilt_deg: float) -> float:
    t = float(tilt_deg)
    if t > 180.0:
        t -= 360.0
    elif t < -180.0:
        t += 360.0
    return t


def entity_basis_columns(pan_deg: float, tilt_deg: float, roll_deg: float) -> list[float]:
    """Conitec ang_to_matrix (DirectX Y-up), conjugated by S=diag(1,1,-1)
    into a right-handed Y-up basis -- same target convention as Godot's
    Basis(x_g, y_g, z_g). Returned as 9 floats, column-major: local +X,
    +Y, +Z axes expressed in world space. Local +X is "forward" by the
    whole pipeline's convention (WED pan=0 -> +X)."""
    p = math.radians(float(pan_deg))
    t = math.radians(_norm_tilt(tilt_deg))
    r = math.radians(float(roll_deg))
    cp, sp = math.cos(p), math.sin(p)
    ct, st = math.cos(t), math.sin(t)
    cr, sr = math.cos(r), math.sin(r)
    x_dx = (ct * cp, st, ct * sp)
    y_dx = (-cr * st * cp + sr * sp, cr * ct, -cr * st * sp - sr * cp)
    z_dx = (-sr * st * cp - cr * sp, sr * ct, cr * cp - sr * st * sp)
    x_g = (x_dx[0], x_dx[1], -x_dx[2])
    y_g = (y_dx[0], y_dx[1], -y_dx[2])
    z_g = (-z_dx[0], -z_dx[1], z_dx[2])
    return [*x_g, *y_g, *z_g]


_YAW_ALLOWLIST_PATH = ROOT / "tools" / "mdl_yaw_allowlist.json"
_yaw_allowlist_cache: dict[str, float] | None = None


def yaw_allowlist() -> dict[str, float]:
    """`extra_yaw_deg` from mdl_yaw_allowlist.json (same file convert_mdl.py
    reads), keyed lowercase stem -- read fresh here too rather than assumed,
    since the arrow gizmo needs to know about it: this correction is baked
    directly into the .glb's vertex data at convert time, so a mesh and the
    "raw pan/tilt/roll" arrow will *always* disagree by this amount for any
    allowlisted model unless the arrow also accounts for it."""
    global _yaw_allowlist_cache
    if _yaw_allowlist_cache is None:
        try:
            data = json.loads(_YAW_ALLOWLIST_PATH.read_text())
            _yaw_allowlist_cache = {k.lower(): float(v) for k, v in data.get("extra_yaw_deg", {}).items()}
        except Exception:
            _yaw_allowlist_cache = {}
    return _yaw_allowlist_cache


def yaw_rotate_y_three(v: tuple[float, float, float], deg: float) -> tuple[float, float, float]:
    """Same rotation convert_mdl.py's _yaw_rotate_y applies to mesh vertices
    (right-handed Y-up, rotate about +Y) -- used here to compute what
    direction the *mesh itself* (after its baked-in allowlist correction)
    actually points, for the arrow gizmo."""
    a = math.radians(deg)
    c, s = math.cos(a), math.sin(a)
    x, y, z = v
    return (x * c + z * s, y, -x * s + z * c)


# --- Feet-snap policy, fresh port of _should_feet_snap in
# scripts/engine/wmb_level_loader.gd (see docs/CONTRACT.md #3) -- entities
# are placed at their raw WED origin by default here, same as this whole
# tool's philosophy of showing raw parsed data, but without any floor
# correction at all every character appears to float/sink relative to
# where the actual game puts them. Ported so the viewer matches Godot's
# real spawn behavior instead of looking wrong in a *third*, new way.
_CAMERA_ACTIONS = {
    "cam", "thecam", "thecam2", "farcam", "scam", "cammy", "lookatme",
    "mycamera", "pipicam", "cam2", "cam3", "cam4", "camplane", "cameraengine",
}
_FEET_SNAP_EXCLUDE_STEMS = {
    "glass", "b747", "tv", "island", "headphon", "biplane",
    "biplane2", "hanger", "towerw", "dutyfree",
}


def should_feet_snap(action: str, stem: str) -> bool:
    a = action.lower()
    s = stem.lower()
    if a in _CAMERA_ACTIONS or s == "cam":
        return False
    if s in {"afg", "shiknote"}:
        return False
    if a == "window":
        return False
    if s in _FEET_SNAP_EXCLUDE_STEMS:
        return False
    if a in {"headphone", "land", "wind", "ent_rotate", "item_pickup"}:
        return False
    return True


def _make_entity_dict(
    name: str, filename: str, action: str,
    ox: float, oy: float, oz: float,
    pan: float, tilt: float, roll: float,
    sx: float, sy: float, sz: float,
    skills: list[float], flags: int,
) -> dict:
    stem = Path(filename).stem.lower() if filename else ""
    mesh_yaw = yaw_allowlist().get(stem, 0.0)
    basis = entity_basis_columns(pan, tilt, roll)
    x_col = basis[0:3]
    y_col = basis[3:6]
    z_col = basis[6:9]
    # Arrow direction = entity basis applied to the mesh's OWN forward,
    # which includes any baked-in mdl_yaw_allowlist.json correction --
    # without this the arrow only shows the raw WMB pan and will disagree
    # with the mesh by exactly the allowlist amount even when everything
    # is working correctly (this was the source of a false-positive "mesh
    # doesn't match arrow" report -- see docs/SESSION_LOG.md 2026-07-27).
    local_fwd = yaw_rotate_y_three((1.0, 0.0, 0.0), mesh_yaw)
    forward = [
        local_fwd[0] * x_col[0] + local_fwd[1] * y_col[0] + local_fwd[2] * z_col[0],
        local_fwd[0] * x_col[1] + local_fwd[1] * y_col[1] + local_fwd[2] * z_col[1],
        local_fwd[0] * x_col[2] + local_fwd[1] * y_col[2] + local_fwd[2] * z_col[2],
    ]
    return {
        "name": name,
        "file": filename,
        "action": action,
        "pos": pos_gs_to_three(ox, oy, oz),
        "pan_tilt_roll_gs": [float(pan), float(tilt), float(roll)],
        "scale": scale_gs_to_three(sx, sy, sz),
        "skills": skills,
        "flags": int(flags),
        "basis": basis,
        "mesh_yaw_deg": mesh_yaw,
        "forward": forward,
        "should_feet_snap": should_feet_snap(action, stem),
    }


def parse_wmb(path: Path) -> dict:
    data = path.read_bytes()
    magic = data[:4]
    lists = _read_lists(data)
    if len(lists) <= 15 or lists[15][1] == 0:
        raise ValueError(f"{path.name}: no object list found (list 15 empty)")

    base, length = lists[15]
    chunk = memoryview(data)[base : base + length]
    count = struct.unpack_from("<I", chunk, 0)[0]
    offsets = list(struct.unpack_from(f"<{count}I", chunk, 4))

    entities: list[dict] = []
    lights: list[dict] = []
    paths: list[dict] = []

    for rel in offsets:
        o = rel
        if o + 4 > len(chunk):
            continue
        typ = struct.unpack_from("<I", chunk, o)[0]
        o += 4

        if typ == 2:  # LIGHT
            ox, oy, oz = struct.unpack_from("<3f", chunk, o)
            o += 12
            r, g, b, rng = struct.unpack_from("<4f", chunk, o)
            lights.append(
                {
                    "pos": pos_gs_to_three(ox, oy, oz),
                    "color": [r / 100.0, g / 100.0, b / 100.0],
                    "range": float(rng),
                }
            )
            continue

        if typ == 6:  # PATH
            try:
                name = _c_str(bytes(chunk[o : o + 20]))
                o += 20
                fnum = struct.unpack_from("<f", chunk, o)[0]
                o += 4
                o += 12  # unused[3]
                num_edges = struct.unpack_from("<I", chunk, o)[0]
                o += 4
                npoints = int(fnum) if fnum >= 1.0 else int(num_edges)
                points = []
                for _ in range(max(npoints, 0)):
                    if o + 12 > len(chunk):
                        break
                    px, py, pz = struct.unpack_from("<3f", chunk, o)
                    o += 12
                    points.append(pos_gs_to_three(px, py, pz))
                paths.append({"name": name or f"path_{len(paths) + 1}", "points": points})
            except struct.error:
                pass
            continue

        if typ == 3:  # OLD ENTITY
            ox, oy, oz = struct.unpack_from("<3f", chunk, o)
            o += 12
            pan, tilt, roll = struct.unpack_from("<3f", chunk, o)
            o += 12
            sx, sy, sz = struct.unpack_from("<3f", chunk, o)
            o += 12
            name = _c_str(bytes(chunk[o : o + 20]))
            o += 20
            filename = _c_str(bytes(chunk[o : o + 13]))
            o += 13
            action = _c_str(bytes(chunk[o : o + 20]))
            o += 20
            o += 3  # pad (float-aligns the skills block)
            skills = list(struct.unpack_from("<8f", chunk, o))
            o += 32
            flags = struct.unpack_from("<I", chunk, o)[0] if o + 4 <= len(chunk) else 0
            entities.append(
                _make_entity_dict(name, filename, action, ox, oy, oz, pan, tilt, roll, sx, sy, sz, skills, flags)
            )
            continue

        if typ == 7:  # ENTITY (new format)
            ox, oy, oz = struct.unpack_from("<3f", chunk, o)
            o += 12
            pan, tilt, roll = struct.unpack_from("<3f", chunk, o)
            o += 12
            sx, sy, sz = struct.unpack_from("<3f", chunk, o)
            o += 12
            name = _c_str(bytes(chunk[o : o + 33]))
            o += 33
            filename = _c_str(bytes(chunk[o : o + 33]))
            o += 33
            action = _c_str(bytes(chunk[o : o + 33]))
            o += 34
            skills = list(struct.unpack_from("<20f", chunk, o))
            o += 80
            flags = struct.unpack_from("<I", chunk, o)[0]
            o += 4
            entities.append(
                _make_entity_dict(name, filename, action, ox, oy, oz, pan, tilt, roll, sx, sy, sz, skills, flags)
            )
            continue

    return {
        "source": path.name,
        "magic": magic.decode("ascii", "replace"),
        "entities": entities,
        "lights": lights,
        "paths": paths,
    }


# --- Model file lookup (reuse already-converted .glb, unmodified) ---------


def _build_index(dir_path: Path) -> dict[str, str]:
    idx: dict[str, str] = {}
    if dir_path.exists():
        for p in dir_path.glob("*.glb"):
            idx[p.stem.lower()] = p.name
    return idx


def resolve_model_url(file_field: str, mdl_index: dict, wmb_index: dict) -> str | None:
    if not file_field:
        return None
    stem = Path(file_field).stem.lower()
    is_wmb = file_field.lower().endswith(".wmb")
    if is_wmb:
        name = wmb_index.get(stem)
        if name:
            return f"/wmb-glb/{name}"
        return None
    name = mdl_index.get(stem)
    if name:
        return f"/mdl-glb/{name}"
    return None


# --- HTTP server ------------------------------------------------------------

VIEWER_HTML = r"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>WMB viewer -- __LEVEL__</title>
<style>
  html, body { margin: 0; height: 100%; background: #14161c; overflow: hidden; font-family: system-ui, sans-serif; }
  #canvas-wrap { position: absolute; inset: 0; }
  #panel {
    position: absolute; top: 8px; left: 8px; width: 340px; max-height: calc(100% - 16px);
    background: rgba(20,22,28,0.92); color: #e8e8ec; border-radius: 8px; padding: 10px 12px;
    overflow-y: auto; font-size: 13px; box-shadow: 0 4px 18px rgba(0,0,0,0.5);
  }
  #panel h1 { font-size: 15px; margin: 0 0 6px; }
  #panel input[type=text], #panel select { width: 100%; box-sizing: border-box; padding: 5px 7px; margin-bottom: 6px;
    background: #23262f; border: 1px solid #3a3f4b; color: #e8e8ec; border-radius: 4px; }
  #level-select { font-weight: 600; }
  #tabs { display: flex; gap: 4px; margin-bottom: 8px; }
  #tabs button { flex: 1; padding: 6px 4px; background: #23262f; border: 1px solid #3a3f4b; color: #b8bcc8;
    border-radius: 5px; cursor: pointer; font-size: 12px; }
  #tabs button.active { background: #3d5a99; color: #fff; border-color: #4d6ab0; }
  .tabpage { display: none; }
  .tabpage.active { display: block; }
  #entity-list { list-style: none; margin: 0; padding: 0; }
  #entity-list li { padding: 3px 6px; border-radius: 4px; cursor: pointer; white-space: nowrap;
    overflow: hidden; text-overflow: ellipsis; }
  #entity-list li:hover { background: #2d3140; }
  #entity-list li.active { background: #3d5a99; }
  #info { margin-top: 8px; padding-top: 8px; border-top: 1px solid #3a3f4b; line-height: 1.5; }
  #info b { color: #9fd3ff; }
  .hint { opacity: 0.65; font-size: 11px; margin-top: 6px; }
  #toggles label { display: block; margin: 2px 0; }
  #status { position: absolute; bottom: 8px; left: 8px; color: #9aa; font-size: 11px; }
  .section-title { font-size: 12px; font-weight: 600; color: #9fd3ff; margin: 10px 0 4px; text-transform: uppercase;
    letter-spacing: 0.03em; }
  .row { display: flex; align-items: center; gap: 6px; margin-bottom: 4px; }
  .row label { flex: 0 0 90px; font-size: 12px; color: #b8bcc8; }
  .row input[type=range] { flex: 1; }
  .row .val { flex: 0 0 44px; font-size: 11px; text-align: right; color: #9fd3ff; font-variant-numeric: tabular-nums; }
  .row input[type=color] { width: 28px; height: 22px; padding: 0; border: none; background: none; cursor: pointer; }
  .light-card { background: #1c1e26; border: 1px solid #2d3140; border-radius: 6px; padding: 6px 8px; margin-bottom: 8px; }
  .light-card .light-title { font-size: 11px; color: #ffcf6b; margin-bottom: 4px; display: flex; justify-content: space-between; }
  button.btn { width: 100%; padding: 7px; margin-top: 4px; background: #2d3140; border: 1px solid #3a3f4b;
    color: #e8e8ec; border-radius: 5px; cursor: pointer; font-size: 12px; }
  button.btn:hover { background: #3a3f52; }
  button.btn.primary { background: #3d5a99; border-color: #4d6ab0; }
  button.btn.primary:hover { background: #4a68ab; }
  #placement-list { list-style: none; margin: 6px 0 0; padding: 0; max-height: 340px; overflow-y: auto; }
  #placement-list li { padding: 4px 6px; border-radius: 4px; cursor: pointer; font-size: 12px; margin-bottom: 2px; }
  #placement-list li:hover { background: #2d3140; }
  #placement-list li.sev-high { border-left: 3px solid #ff5c5c; }
  #placement-list li.sev-med { border-left: 3px solid #ffcf6b; }
  #placement-list .delta { float: right; opacity: 0.8; }
  #export-out { width: 100%; box-sizing: border-box; height: 140px; background: #0e0f13; color: #9fe89f;
    border: 1px solid #3a3f4b; border-radius: 4px; font-family: ui-monospace, monospace; font-size: 11px; padding: 6px; }
  #walk-crosshair { position: absolute; top: 50%; left: 50%; width: 8px; height: 8px; margin: -4px 0 0 -4px;
    border: 1.5px solid #fff; border-radius: 50%; display: none; pointer-events: none; }
  #walk-hint { position: absolute; bottom: 8px; right: 8px; color: #9aa; font-size: 11px; text-align: right; display: none; }
</style>
</head>
<body>
<div id="canvas-wrap"></div>
<div id="walk-crosshair"></div>
<div id="walk-hint">WASD move, mouse look (click canvas to lock), Shift = run, Space = up, C = down, Esc to release</div>
<div id="panel">
  <h1 id="level-title">__LEVEL__.wmb</h1>
  <select id="level-select">__LEVEL_OPTIONS__</select>
  <div id="tabs">
    <button data-tab="inspect" class="active">Inspect</button>
    <button data-tab="lights">Lights</button>
    <button data-tab="placement">Placement</button>
    <button data-tab="walk">Walk</button>
  </div>

  <div id="tab-inspect" class="tabpage active">
    <input type="text" id="search" placeholder="filter by name / file / action...">
    <div id="toggles">
      <label><input type="checkbox" id="chk-brush" checked> brush (walls/floor)</label>
      <label><input type="checkbox" id="chk-arrows" checked> forward arrows (red = local +X)</label>
      <label><input type="checkbox" id="chk-labels"> name labels (can get busy)</label>
      <label><input type="checkbox" id="chk-lights" checked> light markers</label>
    </div>
    <ul id="entity-list"></ul>
    <div id="info">Click an entity (or pick it from the list) to see its data here.</div>
    <div class="hint">Drag to orbit, scroll to zoom, right-drag to pan. Click an entity in the 3D view or in the list.</div>
  </div>

  <div id="tab-lights" class="tabpage">
    <div class="section-title">Global</div>
    <div class="row"><label>Ambient</label><input type="range" id="g-ambient" min="0" max="3" step="0.01" value="0.85"><span class="val" id="g-ambient-v">0.85</span></div>
    <div class="row"><label>Sun energy</label><input type="range" id="g-sun-energy" min="0" max="6" step="0.05" value="2.5"><span class="val" id="g-sun-energy-v">2.5</span></div>
    <div class="row"><label>Sun elevation</label><input type="range" id="g-sun-elev" min="0" max="90" step="1" value="55"><span class="val" id="g-sun-elev-v">55</span></div>
    <div class="row"><label>Sun azimuth</label><input type="range" id="g-sun-azim" min="0" max="360" step="1" value="215"><span class="val" id="g-sun-azim-v">215</span></div>
    <div class="row"><label>Point-light x</label><input type="range" id="g-point-mult" min="0" max="3" step="0.01" value="1"><span class="val" id="g-point-mult-v">1.00</span></div>
    <div class="hint">These mirror the real Godot knobs (ambient_light_energy, Sun.light_energy, per-light energy) --
      sun elevation/azimuth is this tool's own simpler parameterization of Godot's rotation_degrees, close but not
      bit-exact. Point-light-x scales every calibrated light's energy at once, on top of its own per-light slider below.</div>
    <div class="section-title">Per-light (calibrated to real game values)</div>
    <div id="light-cards"></div>
    <button class="btn" id="btn-reset-lights">Reset all to calibrated defaults</button>
    <button class="btn primary" id="btn-export-lights">Copy current tuning as JSON</button>
    <textarea id="export-out" style="display:none" readonly></textarea>
  </div>

  <div id="tab-placement" class="tabpage">
    <div class="hint">Raycasts straight down from each entity's placed position to the brush floor and flags a
      large gap (floating or embedded). Needs the brush (walls/floor) loaded -- most levels have it.</div>
    <button class="btn primary" id="btn-scan-placement">Scan floor placement</button>
    <div id="placement-summary" class="hint"></div>
    <ul id="placement-list"></ul>
  </div>

  <div id="tab-walk" class="tabpage">
    <div class="hint">A simple walk-through camera: WASD to move, mouse to look, floor-snapped like the real
      first-person controller (not full physics -- no real collision against walls yet, just floor height).
      Useful for eyeballing scale, sightlines, and whether a floor reads too high/low without opening Godot.</div>
    <button class="btn primary" id="btn-walk-toggle">Enter walk mode</button>
    <div class="row" style="margin-top:8px"><label>Eye height</label><input type="range" id="walk-eye-h" min="10" max="120" step="1" value="60"><span class="val" id="walk-eye-h-v">60</span></div>
    <div class="row"><label>Move speed</label><input type="range" id="walk-speed" min="20" max="600" step="10" value="180"><span class="val" id="walk-speed-v">180</span></div>
  </div>
</div>
<div id="status">loading...</div>
<script type="importmap">
{
  "imports": {
    "three": "https://unpkg.com/three@0.160.0/build/three.module.js",
    "three/addons/": "https://unpkg.com/three@0.160.0/examples/jsm/"
  }
}
</script>
<script type="module">
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";

const statusEl = document.getElementById("status");

// --- Independent re-implementation of the entity basis math (JS side).
// If this disagrees with what Godot renders for the same pan/tilt/roll,
// that's a real finding -- not the same bug rendered twice. Mirrors
// wmb_web_viewer.py's entity_basis_columns() / Godot's
// _acknex_entity_basis(), written fresh, not copy-pasted from either.
function entityBasisMatrix(panDeg, tiltDeg, rollDeg) {
  let tilt = tiltDeg;
  if (tilt > 180) tilt -= 360; else if (tilt < -180) tilt += 360;
  const p = THREE.MathUtils.degToRad(panDeg);
  const t = THREE.MathUtils.degToRad(tilt);
  const r = THREE.MathUtils.degToRad(rollDeg);
  const cp = Math.cos(p), sp = Math.sin(p);
  const ct = Math.cos(t), st = Math.sin(t);
  const cr = Math.cos(r), sr = Math.sin(r);
  const xDx = new THREE.Vector3(ct * cp, st, ct * sp);
  const yDx = new THREE.Vector3(-cr * st * cp + sr * sp, cr * ct, -cr * st * sp - sr * cp);
  const zDx = new THREE.Vector3(-sr * st * cp - cr * sp, sr * ct, cr * cp - sr * st * sp);
  const xG = new THREE.Vector3(xDx.x, xDx.y, -xDx.z);
  const yG = new THREE.Vector3(yDx.x, yDx.y, -yDx.z);
  const zG = new THREE.Vector3(-zDx.x, -zDx.y, zDx.z);
  const m = new THREE.Matrix4();
  m.makeBasis(xG, yG, zG);
  return m;
}

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x14161c);

// Global lights, tunable live from the "Lights" tab -- ambientLight mirrors
// Godot's ambient_light_energy (level_runner.gd _ensure_environment());
// sunLight mirrors the Sun DirectionalLight3D (same file), parameterized
// as elevation/azimuth here instead of Godot's raw rotation_degrees for a
// friendlier slider even though it means this ISN'T a bit-exact replica of
// Godot's own basis math -- good enough to judge "is this surface reading
// too dark/bright", which is what this tab exists for.
const ambientLight = new THREE.AmbientLight(0xffffff, 0.85);
scene.add(ambientLight);
const sunLight = new THREE.DirectionalLight(0xfff5e0, 2.5);
scene.add(sunLight);
scene.add(sunLight.target);

function updateSunDirection(elevDeg, azimDeg) {
  const elev = THREE.MathUtils.degToRad(elevDeg);
  const azim = THREE.MathUtils.degToRad(azimDeg);
  const dist = 3000;
  sunLight.position.set(
    Math.cos(elev) * Math.cos(azim) * dist,
    Math.sin(elev) * dist,
    Math.cos(elev) * Math.sin(azim) * dist
  );
  sunLight.target.position.set(0, 0, 0);
}
updateSunDirection(55, 215);

// --- Global light slider wiring (tab is built once; scene reloads on
// level switch, but these globals + their DOM elements persist).
function wireSlider(id, valId, fmt, onInput) {
  const el = document.getElementById(id);
  const valEl = document.getElementById(valId);
  const update = () => {
    valEl.textContent = fmt(parseFloat(el.value));
    onInput(parseFloat(el.value));
  };
  el.addEventListener("input", update);
  return update;
}
wireSlider("g-ambient", "g-ambient-v", (v) => v.toFixed(2), (v) => (ambientLight.intensity = v));
wireSlider("g-sun-energy", "g-sun-energy-v", (v) => v.toFixed(2), (v) => (sunLight.intensity = v));
let sunElev = 55, sunAzim = 215;
wireSlider("g-sun-elev", "g-sun-elev-v", (v) => v.toFixed(0), (v) => { sunElev = v; updateSunDirection(sunElev, sunAzim); });
wireSlider("g-sun-azim", "g-sun-azim-v", (v) => v.toFixed(0), (v) => { sunAzim = v; updateSunDirection(sunElev, sunAzim); });
let lightEntries = []; // rebuilt per level load -- {light, point, marker, energySlider, rangeSlider, colorInput, baseIntensityFor}
let pointLightMult = 1.0;
wireSlider("g-point-mult", "g-point-mult-v", (v) => v.toFixed(2), (v) => {
  pointLightMult = v;
  applyPointLightMult();
});
function applyPointLightMult() {
  for (const entry of lightEntries) {
    entry.point.intensity = entry.baseIntensityFor(entry.energySlider.value) * pointLightMult;
  }
}

const wrap = document.getElementById("canvas-wrap");
const camera = new THREE.PerspectiveCamera(60, wrap.clientWidth / wrap.clientHeight, 0.5, 40000);
camera.position.set(400, 500, 800);

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(wrap.clientWidth, wrap.clientHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
// three@0.160 defaults to physically-correct lighting (PointLight
// intensity in candela, real inverse-square decay) with NO tonemap --
// anything past 1.0 just clips flat to white. ACES gives the same
// graceful highlight rolloff this session already added to the real
// Godot game's WorldEnvironment for the same reason (see level_runner.gd
// _ensure_environment()).
renderer.toneMapping = THREE.ACESFilmicToneMapping;
wrap.appendChild(renderer.domElement);

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(0, 0, 0);
controls.update();

window.addEventListener("resize", () => {
  camera.aspect = wrap.clientWidth / wrap.clientHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(wrap.clientWidth, wrap.clientHeight);
});

const grid = new THREE.GridHelper(4000, 40, 0x444a58, 0x2a2e38);
scene.add(grid);
scene.add(new THREE.AxesHelper(150)); // red=+X green=+Y(up) blue=+Z

const gltfLoader = new GLTFLoader();
const modelCache = new Map(); // url -> Promise<Object3D template>

function loadModel(url) {
  if (!modelCache.has(url)) {
    modelCache.set(
      url,
      new Promise((resolve) => {
        gltfLoader.load(
          url,
          (gltf) => resolve(gltf.scene),
          undefined,
          () => resolve(null)
        );
      })
    );
  }
  return modelCache.get(url);
}

// Level-scoped groups/arrays -- cleared and rebuilt on every level switch
// (see clearLevelState() below), not just populated once at page load.
const entityGroup = new THREE.Group();
scene.add(entityGroup);
const lightGroup = new THREE.Group();
scene.add(lightGroup);
const pathGroup = new THREE.Group();
scene.add(pathGroup);
const placementGroup = new THREE.Group();
scene.add(placementGroup);
let labelSprites = [];
let pickable = []; // {mesh, data}
let brushMesh = null; // set once the brush .glb loads, used by the placement scan + walk mode

function clearLevelState() {
  entityGroup.clear();
  lightGroup.clear();
  pathGroup.clear();
  placementGroup.clear();
  labelSprites = [];
  pickable = [];
  brushMesh = null;
  document.getElementById("entity-list").innerHTML = "";
  document.getElementById("light-cards").innerHTML = "";
  document.getElementById("placement-list").innerHTML = "";
  document.getElementById("placement-summary").textContent = "";
  document.getElementById("info").textContent = "Click an entity (or pick it from the list) to see its data here.";
  activeLi = null;
}

function makeLabelSprite(text) {
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  const pad = 8;
  ctx.font = "28px sans-serif";
  const w = Math.ceil(ctx.measureText(text).width) + pad * 2;
  canvas.width = w;
  canvas.height = 40;
  ctx.font = "28px sans-serif";
  ctx.fillStyle = "rgba(10,12,16,0.75)";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = "#fff";
  ctx.fillText(text, pad, 29);
  const tex = new THREE.CanvasTexture(canvas);
  const mat = new THREE.SpriteMaterial({ map: tex, depthTest: false });
  const sprite = new THREE.Sprite(mat);
  sprite.scale.set(canvas.width * 0.6, canvas.height * 0.6, 1);
  return sprite;
}

function addArrow(forwardArr, pos, length, color) {
  // forwardArr already includes both the entity's pan/tilt/roll AND the
  // mesh's own baked-in mdl_yaw_allowlist.json correction (computed
  // server-side in _make_entity_dict) -- so this is what the mesh's own
  // forward SHOULD look like, not just the raw WMB angle.
  const fwd = new THREE.Vector3(...forwardArr).normalize();
  const origin = new THREE.Vector3(...pos);
  const arrow = new THREE.ArrowHelper(fwd, origin, length, color, length * 0.25, length * 0.15);
  entityGroup.add(arrow);
}

async function buildScene(level) {
  clearLevelState();
  document.getElementById("panel").querySelector("h1").textContent =
    `${level.source} -- ${level.entities.length} entities, ${level.lights.length} lights, ${level.paths.length} paths`;

  // Remove any previous level's brush mesh before (maybe) loading a new one.
  const oldBrush = scene.getObjectByName("__brush__");
  if (oldBrush) scene.remove(oldBrush);

  // Brush (walls/floor) for spatial context -- reused as-is from the
  // existing, already-verified extract_wmb_mesh.py output.
  if (level.brush_url) {
    gltfLoader.load(level.brush_url, (gltf) => {
      gltf.scene.traverse((o) => {
        if (o.isMesh) {
          o.material = o.material.clone();
          o.material.side = THREE.DoubleSide;
        }
      });
      gltf.scene.name = "__brush__";
      scene.add(gltf.scene);
      brushMesh = gltf.scene;
      document.getElementById("chk-brush").onchange = (e) => {
        gltf.scene.visible = e.target.checked;
      };
    });
  }

  // Lights: real OmniLight-equivalents + a small visible marker sphere.
  // `l.calibrated_energy` / `l.calibrated_range` come from the server
  // (calibrate_lights() in this same tool's Python half), mirroring the
  // real Godot game's `_spawn_light()` math exactly (GB-44 through
  // GB-49's own shipped values) -- NOT the raw WMB data -- so this
  // viewer's starting point is what the game actually renders, not a
  // fictional uncalibrated light. Reported live (2026-08-17): "the
  // lights are too dim" at the OLD raw-value/intensity=1.2 setup -- fixed
  // then by discovering THREE.PointLight's physically-correct candela
  // decay needs intensity on the order of distance^2 at this scene's
  // scale (hundreds of units, same non-physical mismatch GB-44 found for
  // Godot's own OmniLight3D energy); kept that same conversion here
  // (baseIntensityFor), just driven by the calibrated energy instead of
  // a hardcoded 200000.
  function baseIntensityForEnergy(energy) {
    return 200000 * (energy / 1000);
  }
  const lightMarkerGeo = new THREE.SphereGeometry(6, 8, 8);
  const lightCardsEl = document.getElementById("light-cards");
  lightCardsEl.innerHTML = "";
  lightEntries = [];
  level.lights.forEach((l, i) => {
    const color = new THREE.Color(l.color[0], l.color[1], l.color[2]);
    const dist = l.calibrated_range;
    const energy = l.calibrated_energy;
    const point = new THREE.PointLight(color, baseIntensityForEnergy(energy), dist);
    point.position.set(...l.pos);
    lightGroup.add(point);
    const marker = new THREE.Mesh(lightMarkerGeo, new THREE.MeshBasicMaterial({ color }));
    marker.position.set(...l.pos);
    lightGroup.add(marker);

    const card = document.createElement("div");
    card.className = "light-card";
    const hex = "#" + color.getHexString();
    card.innerHTML = `
      <div class="light-title"><span>Light ${i + 1} @ (${l.pos.map((v) => v.toFixed(0)).join(", ")})</span>
        <input type="color" value="${hex}" data-role="color"></div>
      <div class="row"><label>Energy</label><input type="range" min="0" max="3000" step="10" value="${energy}" data-role="energy"><span class="val" data-role="energy-v">${energy.toFixed(0)}</span></div>
      <div class="row"><label>Range</label><input type="range" min="20" max="2000" step="5" value="${dist}" data-role="range"><span class="val" data-role="range-v">${dist.toFixed(0)}</span></div>
      <div class="hint" data-role="raw">raw WMB range=${l.raw_range.toFixed(0)}</div>
    `;
    lightCardsEl.appendChild(card);
    const energySlider = card.querySelector('[data-role="energy"]');
    const rangeSlider = card.querySelector('[data-role="range"]');
    const energyV = card.querySelector('[data-role="energy-v"]');
    const rangeV = card.querySelector('[data-role="range-v"]');
    const colorInput = card.querySelector('[data-role="color"]');
    const entry = {
      light: l, point, marker, energySlider, rangeSlider, colorInput,
      defaultEnergy: energy, defaultRange: dist, defaultColor: hex,
      baseIntensityFor: (e) => baseIntensityForEnergy(parseFloat(e)),
    };
    energySlider.addEventListener("input", () => {
      energyV.textContent = parseFloat(energySlider.value).toFixed(0);
      point.intensity = baseIntensityForEnergy(parseFloat(energySlider.value)) * pointLightMult;
    });
    rangeSlider.addEventListener("input", () => {
      rangeV.textContent = parseFloat(rangeSlider.value).toFixed(0);
      point.distance = parseFloat(rangeSlider.value);
    });
    colorInput.addEventListener("input", () => {
      const c = new THREE.Color(colorInput.value);
      point.color.copy(c);
      marker.material.color.copy(c);
    });
    lightEntries.push(entry);
  });
  document.getElementById("chk-lights").onchange = (e) => (lightGroup.visible = e.target.checked);

  // Paths: connect points with lines + numbered dots.
  for (const p of level.paths) {
    if (p.points.length < 2) continue;
    const pts = p.points.map((pt) => new THREE.Vector3(...pt));
    const geo = new THREE.BufferGeometry().setFromPoints(pts);
    const line = new THREE.Line(geo, new THREE.LineBasicMaterial({ color: 0xffaa33 }));
    pathGroup.add(line);
  }

  // Entities.
  const listEl = document.getElementById("entity-list");
  const bbox = new THREE.Box3();
  let anyPoint = false;
  const rawAabbCache = new Map(); // model_url -> Box3 in raw mesh-local space

  for (const ent of level.entities) {
    const li = document.createElement("li");
    li.textContent = `${ent.name || "(unnamed)"} [${ent.action || "-"}] ${ent.file}`;
    li.dataset.search = li.textContent.toLowerCase();
    listEl.appendChild(li);

    let pos = ent.pos.slice();
    // Rotation+scale only (no translation yet) -- used both for the final
    // placement matrix and, before that, to feet-snap: same approach as
    // wmb_level_loader.gd's _snap_mesh_feet_to_origin (transform the raw
    // local AABB's 8 corners by this matrix, take the min Y, lift so the
    // lowest point lands on the WED origin plane) instead of placing every
    // entity at its raw, un-snapped WED origin -- which is usually a
    // *reference* point, not the model's own visual floor, so without this
    // everything looks like it's floating or sunk relative to what the
    // actual game shows.
    const rs = entityBasisMatrix(...ent.pan_tilt_roll_gs);
    rs.scale(new THREE.Vector3(...ent.scale));

    let visualAdded = null;
    if (ent.model_url) {
      const template = await loadModel(ent.model_url);
      if (template) {
        if (ent.should_feet_snap) {
          if (!rawAabbCache.has(ent.model_url)) {
            rawAabbCache.set(ent.model_url, new THREE.Box3().setFromObject(template));
          }
          const raw = rawAabbCache.get(ent.model_url);
          if (isFinite(raw.min.x)) {
            let minY = Infinity;
            for (let i = 0; i < 8; i++) {
              const corner = new THREE.Vector3(
                i & 1 ? raw.max.x : raw.min.x,
                i & 2 ? raw.max.y : raw.min.y,
                i & 4 ? raw.max.z : raw.min.z
              ).applyMatrix4(rs);
              minY = Math.min(minY, corner.y);
            }
            if (isFinite(minY)) pos[1] -= minY;
          }
        }
        const inst = template.clone(true);
        inst.traverse((o) => {
          if (o.isMesh) o.material = o.material.clone();
        });
        const m = rs.clone();
        m.setPosition(...pos);
        inst.matrixAutoUpdate = false;
        inst.matrix.copy(m);
        entityGroup.add(inst);
        visualAdded = inst;
        inst.traverse((o) => {
          if (o.isMesh) pickable.push({ mesh: o, data: ent, li });
        });
      }
    }
    if (!visualAdded) {
      const geo = new THREE.ConeGeometry(4, 14, 6);
      geo.rotateZ(-Math.PI / 2); // cone tip along +X
      const mat = new THREE.MeshBasicMaterial({ color: 0x66ccff });
      const cone = new THREE.Mesh(geo, mat);
      const m = rs.clone();
      m.setPosition(...pos);
      cone.matrixAutoUpdate = false;
      cone.matrix.copy(m);
      entityGroup.add(cone);
      pickable.push({ mesh: cone, data: ent, li });
    }

    bbox.expandByPoint(new THREE.Vector3(...pos));
    anyPoint = true;

    addArrow(ent.forward, pos, 45, 0xff3333);

    const label = makeLabelSprite(ent.name || ent.file || "?");
    label.position.set(pos[0], pos[1] + 60, pos[2]);
    label.visible = document.getElementById("chk-labels").checked;
    entityGroup.add(label);
    labelSprites.push(label);

    li.addEventListener("click", () => selectEntity(ent, li, pos));
  }

  document.getElementById("chk-arrows").onchange = (e) => {
    entityGroup.children.forEach((c) => {
      if (c.type === "ArrowHelper") c.visible = e.target.checked;
    });
  };
  document.getElementById("chk-labels").onchange = (e) => {
    labelSprites.forEach((s) => (s.visible = e.target.checked));
  };

  if (anyPoint) {
    const center = bbox.getCenter(new THREE.Vector3());
    const size = bbox.getSize(new THREE.Vector3()).length();
    controls.target.copy(center);
    camera.position.copy(center).add(new THREE.Vector3(size * 0.35, size * 0.35, size * 0.5));
    controls.update();
  }

  statusEl.textContent = `${level.entities.length} entities placed (models loaded where a matching .glb exists; cyan cones otherwise).`;

  // Debug hook for automated inspection (e.g. puppeteer) -- lets an
  // external script read back actual rendered world transforms instead of
  // only trusting the JS source. THREE is a module-scope import so it's
  // otherwise unreachable from outside; expose what's needed to compute a
  // world-space forward vector for any entity by name/file substring.
  window.__WMB_DEBUG__ = {
    THREE,
    camera,
    controls,
    pickable,
    findByFile: (needle) => pickable.filter((p) => p.data.file.toLowerCase().includes(needle.toLowerCase())),
    worldForward: (mesh) => {
      const q = new THREE.Quaternion();
      mesh.getWorldQuaternion(q);
      return new THREE.Vector3(1, 0, 0).applyQuaternion(q).toArray();
    },
    worldPos: (mesh) => {
      const v = new THREE.Vector3();
      mesh.getWorldPosition(v);
      return v.toArray();
    },
    // Camera placed along an explicit world-space forward vector, looking
    // back at the target -- if that forward vector is really where the
    // character faces, the front should be visible from here.
    setForwardCamera: (forwardArr, posArr, dist) => {
      const c = new THREE.Vector3(...posArr);
      const f = new THREE.Vector3(...forwardArr).normalize();
      const camPos = c.clone().addScaledVector(f, dist).add(new THREE.Vector3(0, dist * 0.15, 0));
      camera.position.copy(camPos);
      controls.target.copy(c);
      controls.update();
    },
  };
}

let activeLi = null;
function selectEntity(ent, li, pos) {
  if (activeLi) activeLi.classList.remove("active");
  li.classList.add("active");
  activeLi = li;
  li.scrollIntoView({ block: "nearest" });
  const [pan, tilt, roll] = ent.pan_tilt_roll_gs;
  document.getElementById("info").innerHTML = `
    <div><b>name</b> ${ent.name || "(unnamed)"}</div>
    <div><b>file</b> ${ent.file}</div>
    <div><b>action</b> ${ent.action || "(none)"}</div>
    <div><b>pos (x,y,z godot-space, post feet-snap)</b> ${pos.map((v) => v.toFixed(1)).join(", ")}</div>
    <div><b>pan/tilt/roll (gs deg)</b> ${pan.toFixed(1)}, ${tilt.toFixed(1)}, ${roll.toFixed(1)}</div>
    <div><b>mesh_yaw_deg (mdl_yaw_allowlist.json)</b> ${ent.mesh_yaw_deg}</div>
    <div><b>feet-snapped</b> ${ent.should_feet_snap}</div>
    <div><b>flags</b> ${ent.flags}</div>
  `;
  controls.target.set(...pos);
  controls.update();
}

const raycaster = new THREE.Raycaster();
const mouse = new THREE.Vector2();
renderer.domElement.addEventListener("click", (ev) => {
  const rect = renderer.domElement.getBoundingClientRect();
  mouse.x = ((ev.clientX - rect.left) / rect.width) * 2 - 1;
  mouse.y = -((ev.clientY - rect.top) / rect.height) * 2 + 1;
  raycaster.setFromCamera(mouse, camera);
  const hits = raycaster.intersectObjects(pickable.map((p) => p.mesh), false);
  if (hits.length) {
    const hitMesh = hits[0].object;
    const found = pickable.find((p) => p.mesh === hitMesh);
    if (found) {
      // Use the actual rendered world position (post feet-snap), not the
      // raw un-snapped ent.pos, so the info panel matches what's on screen.
      const worldPos = new THREE.Vector3();
      hitMesh.getWorldPosition(worldPos);
      selectEntity(found.data, found.li, [worldPos.x, worldPos.y, worldPos.z]);
    }
  }
});

document.getElementById("search").addEventListener("input", (e) => {
  const q = e.target.value.toLowerCase();
  document.querySelectorAll("#entity-list li").forEach((li) => {
    li.style.display = li.dataset.search.includes(q) ? "" : "none";
  });
});

// --- Tabs -------------------------------------------------------------
document.querySelectorAll("#tabs button").forEach((btn) => {
  btn.addEventListener("click", () => {
    document.querySelectorAll("#tabs button").forEach((b) => b.classList.remove("active"));
    document.querySelectorAll(".tabpage").forEach((p) => p.classList.remove("active"));
    btn.classList.add("active");
    document.getElementById(`tab-${btn.dataset.tab}`).classList.add("active");
  });
});

// --- Level switching (no server restart -- fetches a different level's
// own /api/level.json and rebuilds the scene in place). ------------------
function loadLevel(name, pushHistory = true) {
  statusEl.textContent = `loading ${name}...`;
  fetch(`/api/level.json?level=${encodeURIComponent(name)}`)
    .then((r) => r.json())
    .then((data) => {
      if (data.error) throw new Error(data.error);
      buildScene(data);
      if (pushHistory) history.pushState({ level: name }, "", `?level=${encodeURIComponent(name)}`);
    })
    .catch((err) => {
      statusEl.textContent = "Failed to load level.json: " + err;
    });
}
document.getElementById("level-select").addEventListener("change", (e) => loadLevel(e.target.value));
window.addEventListener("popstate", (e) => {
  const name = (e.state && e.state.level) || document.getElementById("level-select").value;
  document.getElementById("level-select").value = name;
  loadLevel(name, false);
});

// --- Light panel: reset / export ---------------------------------------
document.getElementById("btn-reset-lights").addEventListener("click", () => {
  document.getElementById("g-ambient").value = 0.85;
  document.getElementById("g-ambient").dispatchEvent(new Event("input"));
  document.getElementById("g-sun-energy").value = 2.5;
  document.getElementById("g-sun-energy").dispatchEvent(new Event("input"));
  document.getElementById("g-point-mult").value = 1;
  document.getElementById("g-point-mult").dispatchEvent(new Event("input"));
  for (const entry of lightEntries) {
    entry.energySlider.value = entry.defaultEnergy;
    entry.energySlider.dispatchEvent(new Event("input"));
    entry.rangeSlider.value = entry.defaultRange;
    entry.rangeSlider.dispatchEvent(new Event("input"));
    entry.colorInput.value = entry.defaultColor;
    entry.colorInput.dispatchEvent(new Event("input"));
  }
});

document.getElementById("btn-export-lights").addEventListener("click", () => {
  const out = {
    level: document.getElementById("level-select").value,
    ambient_light_energy: parseFloat(document.getElementById("g-ambient").value),
    sun_light_energy: parseFloat(document.getElementById("g-sun-energy").value),
    sun_elevation_deg: parseFloat(document.getElementById("g-sun-elev").value),
    sun_azimuth_deg: parseFloat(document.getElementById("g-sun-azim").value),
    point_light_multiplier: pointLightMult,
    lights: lightEntries.map((e, i) => ({
      index: i,
      pos: e.light.pos.map((v) => Math.round(v)),
      raw_wmb_range: e.light.raw_range,
      energy: parseFloat(e.energySlider.value),
      range: parseFloat(e.rangeSlider.value),
      color: e.colorInput.value,
      changed:
        parseFloat(e.energySlider.value) !== e.defaultEnergy ||
        parseFloat(e.rangeSlider.value) !== e.defaultRange ||
        e.colorInput.value !== e.defaultColor,
    })),
  };
  const ta = document.getElementById("export-out");
  ta.style.display = "block";
  ta.value = JSON.stringify(out, null, 2);
  ta.select();
});

// --- Placement scan: raycast every entity straight down onto the brush,
// flag anything that's floating well above or embedded well below where
// it lands, the same class of bug as this session's own real feet-snap
// fixes (docs/CONTRACT.md #3) -- but checkable here in seconds instead of
// a headless Godot run per candidate. ------------------------------------
const placementRaycaster = new THREE.Raycaster();
const SEV_HIGH = 40; // units -- flagged red
const SEV_MED = 15; // units -- flagged yellow
document.getElementById("btn-scan-placement").addEventListener("click", () => {
  const listEl = document.getElementById("placement-list");
  const summaryEl = document.getElementById("placement-summary");
  listEl.innerHTML = "";
  placementGroup.clear();
  if (!brushMesh) {
    summaryEl.textContent = "No brush geometry loaded for this level -- can't check against a floor.";
    return;
  }
  const meshes = [];
  brushMesh.traverse((o) => {
    if (o.isMesh) meshes.push(o);
  });
  const results = [];
  for (const { mesh, data } of pickable) {
    // One raycast per unique entity (pickable has one entry per mesh
    // triangle-group, an entity's model can have several) -- de-dupe by
    // object identity via a WeakSet-like check on data.
    if (data.__placementChecked) continue;
    data.__placementChecked = true;
    const worldPos = new THREE.Vector3();
    mesh.getWorldPosition(worldPos);
    placementRaycaster.set(worldPos.clone().add(new THREE.Vector3(0, 2000, 0)), new THREE.Vector3(0, -1, 0));
    placementRaycaster.far = 6000;
    const hits = placementRaycaster.intersectObjects(meshes, false);
    let delta = null;
    let color = 0x5c9dff;
    if (hits.length) {
      delta = worldPos.y - hits[0].point.y; // >0 floating, <0 embedded
      const absD = Math.abs(delta);
      color = absD > SEV_HIGH ? 0xff5c5c : absD > SEV_MED ? 0xffcf6b : 0x6bff8f;
    } else {
      color = 0xff5c5c; // no floor below at all -- well outside any brush
    }
    results.push({ data, worldPos, delta, color });
    const marker = new THREE.Mesh(new THREE.SphereGeometry(5, 6, 6), new THREE.MeshBasicMaterial({ color }));
    marker.position.copy(worldPos);
    placementGroup.add(marker);
  }
  for (const { data } of pickable) delete data.__placementChecked;

  results.sort((a, b) => Math.abs(b.delta ?? 9999) - Math.abs(a.delta ?? 9999));
  let flagged = 0;
  for (const r of results) {
    const absD = r.delta === null ? Infinity : Math.abs(r.delta);
    if (absD <= SEV_MED) continue;
    flagged++;
    const li = document.createElement("li");
    li.className = absD > SEV_HIGH || r.delta === null ? "sev-high" : "sev-med";
    const label = r.delta === null ? "no floor found below" : r.delta > 0 ? `floating +${r.delta.toFixed(0)}` : `embedded ${r.delta.toFixed(0)}`;
    li.innerHTML = `${r.data.name || r.data.file || "?"} <span class="delta">${label}</span>`;
    li.addEventListener("click", () => {
      controls.target.copy(r.worldPos);
      controls.update();
    });
    listEl.appendChild(li);
  }
  summaryEl.textContent = `${results.length} entities checked, ${flagged} flagged (>${SEV_MED}u off the floor). Green/yellow/red markers placed at each entity's own position.`;
});

// --- Walk mode: a simple pointer-lock FPS-style camera, floor-snapped by
// raycasting down against the brush each frame (no wall collision yet --
// good enough to judge scale/sightlines/floor height, not a full physics
// stand-in). ---------------------------------------------------------------
let walkMode = false;
let walkVel = new THREE.Vector3();
const walkKeys = new Set();
const walkRaycaster = new THREE.Raycaster();
let walkYaw = 0, walkPitch = 0;

function enterWalkMode() {
  if (!brushMesh) {
    alert("No brush geometry loaded for this level -- walk mode needs a floor to stand on.");
    return;
  }
  walkMode = true;
  controls.enabled = false;
  document.getElementById("walk-crosshair").style.display = "block";
  document.getElementById("walk-hint").style.display = "block";
  document.getElementById("btn-walk-toggle").textContent = "Exit walk mode";
  const e = camera.rotation;
  walkYaw = -e.y;
  walkPitch = e.x;
  renderer.domElement.requestPointerLock();
}
function exitWalkMode() {
  walkMode = false;
  controls.enabled = true;
  document.getElementById("walk-crosshair").style.display = "none";
  document.getElementById("walk-hint").style.display = "none";
  document.getElementById("btn-walk-toggle").textContent = "Enter walk mode";
  if (document.pointerLockElement) document.exitPointerLock();
}
document.getElementById("btn-walk-toggle").addEventListener("click", () => {
  if (walkMode) exitWalkMode();
  else enterWalkMode();
});
document.addEventListener("pointerlockchange", () => {
  if (!document.pointerLockElement && walkMode) exitWalkMode();
});
document.addEventListener("mousemove", (e) => {
  if (!walkMode || !document.pointerLockElement) return;
  walkYaw -= e.movementX * 0.0025;
  walkPitch -= e.movementY * 0.0025;
  walkPitch = Math.max(-Math.PI / 2 + 0.05, Math.min(Math.PI / 2 - 0.05, walkPitch));
});
document.addEventListener("keydown", (e) => {
  if (!walkMode) return;
  walkKeys.add(e.code);
  if (e.code === "Escape") exitWalkMode();
});
document.addEventListener("keyup", (e) => walkKeys.delete(e.code));
wireSlider("walk-eye-h", "walk-eye-h-v", (v) => v.toFixed(0), () => {});
wireSlider("walk-speed", "walk-speed-v", (v) => v.toFixed(0), () => {});

function updateWalk(dt) {
  if (!walkMode) return;
  const speed = parseFloat(document.getElementById("walk-speed").value) * (walkKeys.has("ShiftLeft") ? 2.2 : 1);
  const fwd = new THREE.Vector3(Math.sin(walkYaw), 0, Math.cos(walkYaw)).multiplyScalar(-1);
  const right = new THREE.Vector3(fwd.z, 0, -fwd.x);
  const move = new THREE.Vector3();
  if (walkKeys.has("KeyW")) move.add(fwd);
  if (walkKeys.has("KeyS")) move.sub(fwd);
  if (walkKeys.has("KeyD")) move.add(right);
  if (walkKeys.has("KeyA")) move.sub(right);
  if (move.lengthSq() > 0) move.normalize().multiplyScalar(speed * dt);
  camera.position.add(move);

  let vy = 0;
  if (walkKeys.has("Space")) vy += speed * dt;
  if (walkKeys.has("KeyC")) vy -= speed * dt;
  camera.position.y += vy;

  // Floor snap (only when not manually flying via Space/C this frame) --
  // same idea as the real player controller's own floor-follow, simplified:
  // no gravity ramp, just an instant snap to (floor + eye height).
  if (vy === 0 && brushMesh) {
    walkRaycaster.set(camera.position.clone().add(new THREE.Vector3(0, 500, 0)), new THREE.Vector3(0, -1, 0));
    walkRaycaster.far = 3000;
    const meshes = [];
    brushMesh.traverse((o) => {
      if (o.isMesh) meshes.push(o);
    });
    const hits = walkRaycaster.intersectObjects(meshes, false);
    if (hits.length) {
      const eyeH = parseFloat(document.getElementById("walk-eye-h").value);
      camera.position.y = hits[0].point.y + eyeH;
    }
  }

  camera.rotation.set(walkPitch, walkYaw, 0, "YXZ");
}

// --- Boot ---------------------------------------------------------------
const initialLevel = new URLSearchParams(location.search).get("level") || document.getElementById("level-select").value;
document.getElementById("level-select").value = initialLevel;
loadLevel(initialLevel, false);

let lastT = performance.now();
(function animate() {
  requestAnimationFrame(animate);
  const now = performance.now();
  const dt = Math.min((now - lastT) / 1000, 0.1);
  lastT = now;
  updateWalk(dt);
  if (!walkMode) controls.update();
  renderer.render(scene, camera);
})();
</script>
</body>
</html>
"""


class Handler(BaseHTTPRequestHandler):
    # Small in-process cache -- parsing + calibrating a level is fast
    # (well under a second) but there's no reason to redo it on every
    # dropdown flick back to a level already visited this session.
    _level_cache: dict[str, dict] = {}

    def __init__(self, *args, levels: list[str], initial_level: str, **kwargs):
        self._levels = levels
        self._initial_level = initial_level
        super().__init__(*args, **kwargs)

    def log_message(self, fmt, *args):  # quieter console
        pass

    def _send_bytes(self, data: bytes, content_type: str) -> None:
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(data)

    def _send_file(self, path: Path, content_type: str) -> None:
        if not path.exists():
            self.send_error(404)
            return
        self._send_bytes(path.read_bytes(), content_type)

    def _get_level(self, level: str) -> dict | None:
        if level not in self._levels:
            return None
        if level not in Handler._level_cache:
            print(f"Loading {level}...")
            Handler._level_cache[level] = load_level(level)
        return Handler._level_cache[level]

    def do_GET(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        path = unquote(parsed.path)
        query = {k: v[-1] for k, v in parse_qs(parsed.query).items()}

        if path == "/" or path == "":
            level = query.get("level", self._initial_level)
            if level not in self._levels:
                level = self._initial_level
            # Plain .replace(), not .format() -- the HTML/CSS/JS below is
            # full of literal `{...}` (CSS rules, JS objects, the import
            # map) that .format() would try to parse as placeholders and
            # crash on (this broke every request to "/" the first time).
            html = VIEWER_HTML.replace("__LEVEL__", level).replace(
                "__LEVEL_OPTIONS__",
                "\n".join(
                    f'<option value="{lvl}"{" selected" if lvl == level else ""}>{lvl}</option>' for lvl in self._levels
                ),
            )
            self._send_bytes(html.encode("utf-8"), "text/html; charset=utf-8")
        elif path == "/api/level.json":
            level = query.get("level", self._initial_level)
            try:
                data = self._get_level(level)
            except Exception as exc:  # noqa: BLE001 -- surface any parse error to the browser, not a bare 500
                self._send_bytes(json.dumps({"error": str(exc)}).encode("utf-8"), "application/json")
                return
            if data is None:
                self.send_error(404, f"Unknown level {level!r}")
                return
            self._send_bytes(json.dumps(data).encode("utf-8"), "application/json")
        elif path.startswith("/mdl-glb/"):
            self._send_file(MDL_GLB_DIR / path[len("/mdl-glb/") :], "model/gltf-binary")
        elif path.startswith("/wmb-glb/"):
            self._send_file(WMB_GLB_DIR / path[len("/wmb-glb/") :], "model/gltf-binary")
        elif path.startswith("/brush-glb/"):
            self._send_file(LEVEL_JSON_DIR / path[len("/brush-glb/") :], "model/gltf-binary")
        else:
            self.send_error(404)


def list_available_levels() -> list[str]:
    if not WMB_SRC_DIR.exists():
        return []
    return sorted({p.stem for p in WMB_SRC_DIR.glob("*.[Ww][Mm][Bb]")}, key=str.lower)


def load_level(level: str) -> dict:
    wmb_path = None
    for ext in (".WMB", ".wmb"):
        cand = WMB_SRC_DIR / (level + ext)
        if cand.exists():
            wmb_path = cand
            break
    if wmb_path is None:
        raise FileNotFoundError(f"Could not find {level}.WMB under {WMB_SRC_DIR}")

    ensure_cache_warm(level)
    level_data = parse_wmb(wmb_path)
    calibrate_lights(level_data["lights"])

    mdl_index = _build_index(MDL_GLB_DIR)
    wmb_index = _build_index(WMB_GLB_DIR)
    for ent in level_data["entities"]:
        ent["model_url"] = resolve_model_url(ent["file"], mdl_index, wmb_index)

    brush_path = LEVEL_JSON_DIR / f"{level}_brush.glb"
    level_data["brush_url"] = f"/brush-glb/{level}_brush.glb" if brush_path.exists() else None
    return level_data


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "level",
        nargs="?",
        default="Start",
        help="Initial level to show, e.g. Start -- switch levels live in the browser afterward, no restart needed",
    )
    ap.add_argument("--port", type=int, default=8765)
    ap.add_argument("--no-browser", action="store_true")
    args = ap.parse_args()

    levels = list_available_levels()
    if not levels:
        print(f"No .WMB files found under {WMB_SRC_DIR}", file=sys.stderr)
        return 1
    initial = args.level if args.level in levels else levels[0]

    handler_cls = partial(Handler, levels=levels, initial_level=initial)
    server = ThreadingHTTPServer(("127.0.0.1", args.port), handler_cls)
    url = f"http://127.0.0.1:{args.port}/?level={initial}"
    print(f"{len(levels)} levels available. Serving on {url}  (Ctrl+C to stop)")
    print("Switch levels live via the in-page dropdown -- no server restart needed.")
    if not args.no_browser:
        threading.Timer(0.5, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
